<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>抽号机安装器</AssemblyName>
    <RootNamespace>DrawMachineInstaller</RootNamespace>
    <ApplicationIcon>Assets\app-icon.ico</ApplicationIcon>
    <Version>176.0.0</Version>
    <FileVersion>176.0.0.0</FileVersion>
    <InformationalVersion>v176-2026-09-12</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\app-icon.ico" />
    <EmbeddedResource Include="Payload\DrawMachine.exe" LogicalName="DrawMachine.exe" />
  </ItemGroup>
</Project>
