<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>抽号机</AssemblyName>
    <RootNamespace>DrawMachineDesktop</RootNamespace>
    <ApplicationIcon>Assets\app-icon.ico</ApplicationIcon>
    <Version>175.0.0</Version>
    <FileVersion>175.0.0.0</FileVersion>
    <InformationalVersion>v175-2026-08-25</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\app-icon.ico" />
  </ItemGroup>
</Project>
